---
docker_kernel_min_version: '0'

# Override defaults, missing 17.03 for aarch64
docker_version: '1.13'

# http://mirror.centos.org/altarch/7/extras/aarch64/Packages/
# or do 'yum --showduplicates list docker'
docker_versioned_pkg:
  'latest': docker-ce
  '1.13': docker-1.13.1-103.git7f2769b.el7
  '18.03': docker-ce-18.03.1.ce-1.el7.centos
  '18.06': docker-ce-18.06.2.ce-3.el7
  '18.09': docker-ce-18.09.5-3.el7
  'stable': docker-ce-18.09.5-3.el7
  'edge': docker-ce-18.09.5-3.el7

# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/7/aarch64/stable/Packages/

docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
